### ISSUE TITLE
dexy.controller.find_filters is broken

### ISSUE THREAD

**Issue by nirs** [dexy/dexy#1]
Seems that the code works only when dexy is run from a development work tree, where dexy filters are located at "dexy/dexy/filters", but no dexy filter is loaded when dexy is installed, and its path is something like: "dexy-0.5.0-py2.7.egg/dexy/filters". The results is empty filters and confusing error messages.

**Comment by ananelson** [comment]
Yes, I had this too. I moved the location of dexy filters and it confuses things unless you do a clean reinstall.

Can you try uninstalling + reinstalling dexy and let me know if that fixes things for you.

**Comment by nirs** [comment]
This patch http://nirs.freeshell.org/dexy/0001-Fix-load_filters-when-package-is-installed.patch fix this by specifying the package instead of guessing it from the path.

**Comment by ananelson** [comment]
I've replicated this and your patch seems like a nice way to fix this, it will be in 0.5.0. Thanks.
