### ISSUE TITLE
Dexy Getting Started Guide

### ISSUE THREAD

**Issue by emcee21** [dexy/dexy#112]
In the HTML example it looks like you ended the code to be

from cmath import phase
print phase(complex(-1.0, 0.0))

but instead script.py includes

for i in range(0, 5):
    print i

**Comment by mikejbrown** [comment]
Note the code for all these examples is actually kept in a separate repository: https://github.com/ananelson/dexy-guide-templates :see_no_evil: 
I'll see what I can do...

**Comment by mikejbrown** [comment]
Pull request here https://github.com/ananelson/dexy-guide-templates/pull/1
