### ISSUE TITLE
idio sections for sql scripts

### ISSUE THREAD

**Issue by Arkoniak** [dexy/dexy#125]
Unfortunately, sql do not support '//' or '#' type of comments. Only comments types that is allowed are 
- -- < comment >
- /\* < comment > */

Is it possible to tune idio somehow, so it would be possible to create sections like this:
--- @export "some_query"
or like this
/\* section "some_query" */

**Comment by ananelson** [comment]
You can write comments like:

```
/*** @foo */
```

Would this work?

**Comment by ananelson** [comment]
Some new documentation on available comment formats:
http://dexy.it/ref/filters/htmlsections.html#examples

**Comment by Arkoniak** [comment]
Thank you, /**\* @foo */ is working just fine.
