### ISSUE TITLE
dexy-0.5.2 does not install due to missing LICENSE file

### ISSUE THREAD

**Issue by salestial** [dexy/dexy#8]
I am getting the following error while trying to install dexy:

> > > warning: install_data: setup script did not provide a directory for 'LICENSE' -- installing right in '/usr/local'
> > > error: can't copy 'LICENSE': doesn't exist or not a regular file

I get the same error whether I use pip install or install from the tarball.

It could possibly be related to the requirement "zapps" which is listed as dead by its author???

I have found a temporary workaround by issuing the command "touch LICENSE" in the setup.py directory and tricking the installer (it then installs without a problem) but I think we need a more permanent fix.

**Comment by ananelson** [comment]
This should be fixed now. I think it was only showing up in newer versions of virtualenv. I have stopped trying to copy the LICENSE file altogether.
