### ISSUE TITLE
Learn X the Hard Way

### ISSUE THREAD

**Issue by evelynmitchell** [dexy/dexy#85]
https://gitorious.org/learn-x-the-hard-way/learn-x-the-hard-way/source/663fd4f6afd17f9d16fe10bafe3e64fdfb29e629:

The templates for making your own "Learn Python The Hard Way" for your own favorite language, use dexy.

I thought that was cool, and thought you'd like to know.

**Comment by ananelson** [comment]
I think it's cool too! Thanks :-)
